create table "public"."topic" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying default ''::character varying
);


alter table "public"."topic" enable row level security;

CREATE UNIQUE INDEX topic_pkey ON public.topic USING btree (id);

alter table "public"."topic" add constraint "topic_pkey" PRIMARY KEY using index "topic_pkey";

grant delete on table "public"."topic" to "anon";

grant insert on table "public"."topic" to "anon";

grant references on table "public"."topic" to "anon";

grant select on table "public"."topic" to "anon";

grant trigger on table "public"."topic" to "anon";

grant truncate on table "public"."topic" to "anon";

grant update on table "public"."topic" to "anon";

grant delete on table "public"."topic" to "authenticated";

grant insert on table "public"."topic" to "authenticated";

grant references on table "public"."topic" to "authenticated";

grant select on table "public"."topic" to "authenticated";

grant trigger on table "public"."topic" to "authenticated";

grant truncate on table "public"."topic" to "authenticated";

grant update on table "public"."topic" to "authenticated";

grant delete on table "public"."topic" to "service_role";

grant insert on table "public"."topic" to "service_role";

grant references on table "public"."topic" to "service_role";

grant select on table "public"."topic" to "service_role";

grant trigger on table "public"."topic" to "service_role";

grant truncate on table "public"."topic" to "service_role";

grant update on table "public"."topic" to "service_role";


